export default () => ({ businesses:
   [ { id: '-Ve2_hHfPczRX159xt0BCg',
       alias: 'ye-olde-cheshire-cheese-london',
       name: 'Ye Olde Cheshire Cheese',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/ueBvr7vPAW0TfTAN0OxXXw/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/ye-olde-cheshire-cheese-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 296,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442073536170',
       display_phone: '+44 20 7353 6170',
       distance: 1999.0621866394442 },
     { id: 'J73IF_X4CVH28Urr79qyKA',
       alias: 'the-original-shoreditch-pub-crawl-london',
       name: 'The Original Shoreditch Pub Crawl',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/eOotxE8lXkQjV76JYa8bZA/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-original-shoreditch-pub-crawl-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 1,
       categories: [Array],
       rating: 5,
       coordinates: [Object],
       transactions: [],
       price: '£',
       location: [Object],
       phone: '+442038297229',
       display_phone: '+44 20 3829 7229',
       distance: 4267.180235826855 },
     { id: 'hGiblm0l67sLGTtsMvx51A',
       alias: 'the-churchill-arms-london',
       name: 'The Churchill Arms',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/eDfzFGKTrBK8v2enBxMBWg/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-churchill-arms-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 273,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442077274242',
       display_phone: '+44 20 7727 4242',
       distance: 4124.3502895415095 },
     { id: 'n_oGHFO88muDRn6vgQLjqw',
       alias: 'princess-louise-london-2',
       name: 'Princess Louise',
       image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/3oC1Nu1a-UXMo-iAeM8Urw/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/princess-louise-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 126,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442074058816',
       display_phone: '+44 20 7405 8816',
       distance: 1112.028049897214 },
     { id: 'FJs1PrhFMFVL_iMcH69VuQ',
       alias: 'the-grenadier-london',
       name: 'The Grenadier',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/lGspoDchZa6uo3qDrSA_bA/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-grenadier-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 159,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072353074',
       display_phone: '+44 20 7235 3074',
       distance: 1826.8454804863936 },
     { id: 'NEAPxGZfFuGZf8pjC2yhWQ',
       alias: 'the-blackfriar-london',
       name: 'The Blackfriar',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/CZLO5LM2K_VNabFv89y-dA/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-blackfriar-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 125,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072365474',
       display_phone: '+44 20 7236 5474',
       distance: 2231.521060343169 },
     { id: '-uzz2p0W3eDAOqSBHgw-fQ',
       alias: 'lamb-and-flag-london-2',
       name: 'Lamb & Flag',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/z6_AQpOI6pMEA4G9iZvHQw/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/lamb-and-flag-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 112,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442074979504',
       display_phone: '+44 20 7497 9504',
       distance: 719.1170647692165 },
     { id: 'lVn3qBXylytx6BxrTzCpLQ',
       alias: 'the-chandos-london',
       name: 'The Chandos',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/_7FTuXrkcZnqffm3jlgz0A/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-chandos-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 122,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '£',
       location: [Object],
       phone: '+442078361401',
       display_phone: '+44 20 7836 1401',
       distance: 729.771036358222 },
     { id: '1i-iUdP2GKs10_lduricuQ',
       alias: 'the-harp-london-2',
       name: 'The Harp',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/QfRq0nGIdFzchFitiod5JQ/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-harp-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 123,
       categories: [Array],
       rating: 4.5,
       coordinates: [Object],
       transactions: [],
       price: '£',
       location: [Object],
       phone: '+442078360291',
       display_phone: '+44 20 7836 0291',
       distance: 778.0252696186084 },
     { id: 'QI8guDlv3zxMYo_2l5SJJQ',
       alias: 'the-nags-head-london-3',
       name: 'The Nag\'s Head',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/kLjzu_lnXL_LPbTDLj-CBQ/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-nags-head-london-3?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 36,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072351135',
       display_phone: '+44 20 7235 1135',
       distance: 1950.5697647772065 },
     { id: '5fk8f77KL2XAGTW9udwwCw',
       alias: 'the-gunmakers-london-2',
       name: 'The Gunmakers',
       image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/76S4oJh8RdkvBXwUPkEpsA/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-gunmakers-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 53,
       categories: [Array],
       rating: 4.5,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072781022',
       display_phone: '+44 20 7278 1022',
       distance: 2092.013369538216 },
     { id: 'gnkQ-UbIX-vYWR-Rf_IcEQ',
       alias: 'ye-olde-mitre-inn-london',
       name: 'Ye Olde Mitre Inn',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/8Ak5mGC8go7Yfy52gJnqxw/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/ye-olde-mitre-inn-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 57,
       categories: [Array],
       rating: 4.5,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442074054751',
       display_phone: '+44 20 7405 4751',
       distance: 2070.288252318426 },
     { id: 'HntBHodgbw-vhW3MaCqbcw',
       alias: 'the-windsor-castle-london-2',
       name: 'The Windsor Castle',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/drKSLvxsTquRUpi0GSrfYw/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-windsor-castle-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 110,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072438797',
       display_phone: '+44 20 7243 8797',
       distance: 4405.465244691853 },
     { id: '1PyjE90V1QK1AUfcAOD6YQ',
       alias: 'cittie-of-yorke-london',
       name: 'Cittie of Yorke',
       image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/0V1cJaAaEk5PGJMaGZFpcQ/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/cittie-of-yorke-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 66,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '£',
       location: [Object],
       phone: '+442072427670',
       display_phone: '+44 20 7242 7670',
       distance: 1666.7547350010848 },
     { id: 'xouHUGexW5aBcrC60rx9kw',
       alias: 'the-mayflower-london',
       name: 'The Mayflower',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/Lq0N9bbbKmWSkrRVeHxRpw/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-mayflower-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 78,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072374088',
       display_phone: '+44 20 7237 4088',
       distance: 5831.608478843023 },
     { id: 'S5pre-qmMcQnP_7-cJ4QBg',
       alias: 'seven-stars-london-3',
       name: 'Seven Stars',
       image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/NO-WxiA7eQFzo_1UBTAVkQ/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/seven-stars-london-3?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 56,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072428521',
       display_phone: '+44 20 7242 8521',
       distance: 1548.2680994307234 },
     { id: '917hVPo2F-AZ2R-2uDwJeA',
       alias: 'the-warrington-hotel-london-2',
       name: 'The Warrington Hotel',
       image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/Yb1PU6kwGn78AwYuhXKhlg/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-warrington-hotel-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 67,
       categories: [Array],
       rating: 3.5,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072868282',
       display_phone: '+44 20 7286 8282',
       distance: 3633.2961517478097 },
     { id: 'zfuLEhQFh-m75guUYF_S5A',
       alias: 'the-rose-pub-london-2',
       name: 'The Rose Pub',
       image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/V6Uj-rFP2BiGZ0mT-KppIQ/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-rose-pub-london-2?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 28,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442077311832',
       display_phone: '+44 20 7731 1832',
       distance: 5483.157111580437 },
     { id: 'TKrgGHkG3zZQyHbXLWVGiA',
       alias: 'the-grapes-london',
       name: 'The Grapes',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/yNUg4RY10WT2Ku_NQxXgIQ/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/the-grapes-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 44,
       categories: [Array],
       rating: 4.5,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442079874396',
       display_phone: '+44 20 7987 4396',
       distance: 7072.645818652105 },
     { id: 'By_GidVlsMQa_Ri2hLkP9Q',
       alias: 'waxy-o-connors-london',
       name: 'Waxy O\'Connor\'s',
       image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/x3Q7SC5mr7sA7bTagmWlpA/o.jpg',
       is_closed: false,
       url: 'https://www.yelp.com/biz/waxy-o-connors-london?adjust_creative=WaevPI-Qm0VTDjPJUMr8GA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WaevPI-Qm0VTDjPJUMr8GA',
       review_count: 148,
       categories: [Array],
       rating: 4,
       coordinates: [Object],
       transactions: [],
       price: '££',
       location: [Object],
       phone: '+442072870255',
       display_phone: '+44 20 7287 0255',
       distance: 343.497932226086 } ],
  total: 3200,
  region:
   { center: { longitude: -0.135955810546875, latitude: 51.51283552118349 } } })